---
AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Role for Github OIDC provider

Resources:
  GithubOIDCRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GithubFootballEmailOIDCRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: repo:moritzkoerber/football-schedule-email-service:*
      Path: /
      Policies:
        - PolicyName: Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowUploadToS3Bucket
                Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - 'arn:aws:s3:::football-text-bucket-staging'
                  - 'arn:aws:s3:::football-text-bucket-staging/*'
                  - 'arn:aws:s3:::football-text-bucket-production'
                  - 'arn:aws:s3:::football-text-bucket-production/*'
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource:
                  - !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/*'
              - Effect: Allow
                Action:
                  - s3:*
                  - iam:*
                  - glue:*
                  - athena:*
                  - lambda:*
                  - events:*
                  - cloudwatch:*
                  - logs:*
                  - dynamodb:*
                  - ses:*
                  - sqs:*
                Resource: '*'
                Condition:
                  StringEquals:
                    aws:CalledViaFirst: cloudformation.amazonaws.com
