---
AWSTemplateFormatVersion: '2010-09-09'
Description: ECR Repositories Stack

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - staging
      - production
    Default: staging

Resources:
  EmailLambdaECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageTagMutability: MUTABLE
      ImageScanningConfiguration:
        ScanOnPush: true
      RepositoryName: !Sub 'football_email_lambda-${Environment}'
