---
AWSTemplateFormatVersion: '2010-09-09'
Description: Football SNS Stack

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: FootballEmailNotifications
      TopicName: FootballEmailNotifications

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: '{{resolve:secretsmanager:CloudWatchAlarmEmail:SecretString:email}}'
      Protocol: email
      TopicArn: !Ref SNSTopic
      DeliveryPolicy:
        healthyRetryPolicy:
          minDelayTarget: 20
          maxDelayTarget: 20
          numRetries: 3
          numMaxDelayRetries: 0
          numNoDelayRetries: 0
          numMinDelayRetries: 0
          backoffFunction: linear

Outputs:
  SNSTopic:
    Description: SNS topic for notification and alarm emails
    Value: !Ref SNSTopic
    Export:
      Name: FootballEmailNotifications
