---
name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - staging
          - production
        description: Deploy environment; staging or production
        required: true

concurrency: ${{ github.event.inputs.environment }}

env:
  PYTHON_VERSION: '3.9.9'

permissions:
  id-token: write
  contents: write

jobs:
  deploy_lambda_zip:
    name: Deploy Lambda zip file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup environment
        run: pip install pipenv

      - name: Create requirements
        run: pipenv requirements > requirements.txt

      - name: build zip
        run: |
          pip install --target package -r requirements.txt --no-deps
          rsync -a --exclude='**/__pycache__*' src/. package/
          pushd package && zip -r ../email-lambda-deployment-package.zip . && popd

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubFootballEmailOIDCRole
          aws-region: eu-central-1

      - name: Upload to s3
        run: |
          aws s3 cp email-lambda-deployment-package.zip s3://football-text-bucket-${{ github.event.inputs.environment }}/email-lambda-deployment-package.zip
